name: Update pre-commit config
'on':
  workflow_dispatch: null
jobs:
  update-pre-commit:
    if: github.repository_owner == 'z1fkoisp'
    name: Autoupdate pre-commit config
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v5
    - uses: actions/cache@v4
      with:
        path: ~/.cache/pre-commit
        key: pre-commit-autoupdate
    - name: Update pre-commit config packages
      uses: technote-space/create-pr-action@v2
      with:
        GITHUB_TOKEN: ${{ secrets.ACTION_TRIGGER_TOKEN }}
        EXECUTE_COMMANDS: 'pip install pre-commit

          pre-commit autoupdate || (exit 0);

          pre-commit run -a || (exit 0);

          '
        COMMIT_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        COMMIT_MESSAGE: "\u2B06\uFE0F UPGRADE: Autoupdate pre-commit config"
        PR_BRANCH_NAME: pre-commit-config-update-${PR_ID}
        PR_TITLE: "\u2B06\uFE0F UPGRADE: Autoupdate pre-commit config"
