name: Codeowners Validator
'on':
  push:
    branches:
    - main
  pull_request_target: null
  workflow_dispatch: null
jobs:
  validate:
    name: Validate
    if: github.repository_owner == 'z1fkoisp'
    runs-on: ubuntu-latest
    steps:
    - name: show event name
      run: echo "${{ github.event_name }}"
    - name: Checkout pull request
      if: github.event_name == 'pull_request_target'
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Checkout repo
      if: github.event_name != 'pull_request_target'
      uses: actions/checkout@v4
    - name: GitHub CODEOWNERS Validator
      uses: mszostok/codeowners-validator@v0.7.4
      with:
        checks: files,owners,duppatterns
        experimental_checks: notowned
        github_access_token: ${{ secrets.OWNERS_VALIDATOR_GITHUB_SECRET }}
